services:
  - type: web
    name: mtg-search-chile
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /health
    autoDeployTrigger: off
