create extension if not exists pgcrypto;
create extension if not exists pg_cron;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'app_role') then
    create type public.app_role as enum ('user', 'admin');
  end if;
  if not exists (select 1 from pg_type where typname = 'account_status') then
    create type public.account_status as enum ('active', 'suspended');
  end if;
end
$$;

create table if not exists private.app_config (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  display_name text,
  avatar_url text,
  provider text not null default 'google',
  role public.app_role not null default 'user',
  status public.account_status not null default 'active',
  last_seen_at timestamptz,
  deletion_requested_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists profiles_email_lower_idx
  on public.profiles (lower(email));
create index if not exists profiles_role_status_idx
  on public.profiles (role, status);

create table if not exists public.stores (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique,
  platform text not null check (platform in ('shopify', 'woocommerce', 'jumpseller', 'marketplace')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.favorite_stores (
  user_id uuid not null references public.profiles(id) on delete cascade,
  store_id bigint not null references public.stores(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, store_id)
);

create table if not exists public.wishlist_items (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  card_key text not null,
  card_name text not null,
  desired_quantity integer not null default 1 check (desired_quantity between 1 and 999),
  notes text check (char_length(notes) <= 1000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, card_key)
);

create index if not exists wishlist_items_user_created_idx
  on public.wishlist_items (user_id, created_at desc);

create table if not exists public.search_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  query_text text not null check (char_length(query_text) <= 20000),
  status text not null default 'completed' check (status in ('completed', 'partial', 'failed')),
  card_count integer not null check (card_count between 1 and 100),
  result_count integer not null default 0 check (result_count >= 0),
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  error_summary text check (char_length(error_summary) <= 2000),
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists search_runs_user_created_idx
  on public.search_runs (user_id, created_at desc);
create index if not exists search_runs_created_idx
  on public.search_runs (created_at);

create table if not exists public.search_cards (
  id uuid primary key default gen_random_uuid(),
  search_run_id uuid not null references public.search_runs(id) on delete cascade,
  card_key text not null,
  searched_name text not null,
  canonical_name text,
  scryfall_id text,
  image_url text,
  usd_price numeric(10, 2),
  created_at timestamptz not null default now(),
  unique (search_run_id, card_key)
);

create index if not exists search_cards_run_idx
  on public.search_cards (search_run_id);

create table if not exists public.search_results (
  id uuid primary key default gen_random_uuid(),
  search_card_id uuid not null references public.search_cards(id) on delete cascade,
  store_id bigint not null references public.stores(id),
  product_name text not null,
  price_clp integer not null check (price_clp >= 0),
  product_url text not null,
  in_stock boolean not null default true,
  platform text not null,
  purchase_snapshot jsonb not null default '{}'::jsonb,
  captured_at timestamptz not null default now()
);

create index if not exists search_results_card_price_idx
  on public.search_results (search_card_id, price_clp);
create index if not exists search_results_store_captured_idx
  on public.search_results (store_id, captured_at desc);

create table if not exists public.cart_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  search_run_id uuid references public.search_runs(id) on delete set null,
  store_id bigint references public.stores(id) on delete set null,
  platform text not null,
  event_type text not null default 'cart_opened' check (event_type in ('cart_opened', 'product_opened')),
  estimated_total_clp integer check (estimated_total_clp is null or estimated_total_clp >= 0),
  card_count integer not null default 1 check (card_count between 1 and 100),
  items jsonb not null default '[]'::jsonb,
  destination_url text not null,
  created_at timestamptz not null default now()
);

create index if not exists cart_events_user_created_idx
  on public.cart_events (user_id, created_at desc);
create index if not exists cart_events_created_idx
  on public.cart_events (created_at);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_user_id uuid references public.profiles(id) on delete set null,
  target_user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_created_idx
  on public.admin_audit_log (created_at desc);

create or replace function private.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function private.set_updated_at();

drop trigger if exists stores_set_updated_at on public.stores;
create trigger stores_set_updated_at
before update on public.stores
for each row execute function private.set_updated_at();

drop trigger if exists wishlist_set_updated_at on public.wishlist_items;
create trigger wishlist_set_updated_at
before update on public.wishlist_items
for each row execute function private.set_updated_at();

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  configured_admin text;
  assigned_role public.app_role := 'user';
begin
  select lower(value) into configured_admin
  from private.app_config
  where key = 'initial_admin_email';

  if configured_admin is not null and lower(new.email) = configured_admin then
    assigned_role := 'admin';
  end if;

  insert into public.profiles (
    id, email, display_name, avatar_url, provider, role, last_seen_at
  ) values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data ->> 'avatar_url', new.raw_user_meta_data ->> 'picture'),
    coalesce(new.raw_app_meta_data ->> 'provider', 'google'),
    assigned_role,
    now()
  )
  on conflict (id) do update set
    email = excluded.email,
    display_name = coalesce(public.profiles.display_name, excluded.display_name),
    avatar_url = coalesce(excluded.avatar_url, public.profiles.avatar_url),
    provider = excluded.provider,
    last_seen_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of email, raw_user_meta_data, raw_app_meta_data on auth.users
for each row execute function private.handle_new_user();

-- El trigger cubre altas futuras; esta inserción incorpora usuarios preexistentes.
insert into public.profiles (
  id, email, display_name, avatar_url, provider, role, last_seen_at
)
select
  u.id,
  u.email,
  coalesce(u.raw_user_meta_data ->> 'full_name', u.raw_user_meta_data ->> 'name', split_part(u.email, '@', 1)),
  coalesce(u.raw_user_meta_data ->> 'avatar_url', u.raw_user_meta_data ->> 'picture'),
  coalesce(u.raw_app_meta_data ->> 'provider', 'google'),
  case
    when lower(u.email) = (
      select lower(value) from private.app_config where key = 'initial_admin_email'
    ) then 'admin'::public.app_role
    else 'user'::public.app_role
  end,
  now()
from auth.users u
where u.email is not null
on conflict (id) do update set
  email = excluded.email,
  display_name = coalesce(public.profiles.display_name, excluded.display_name),
  avatar_url = coalesce(excluded.avatar_url, public.profiles.avatar_url),
  provider = excluded.provider;

create or replace function private.is_active_user(requested_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.profiles
    where id = requested_user_id and status = 'active'
  );
$$;

create or replace function private.is_admin(requested_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.profiles
    where id = requested_user_id and role = 'admin' and status = 'active'
  );
$$;

revoke all on function private.handle_new_user() from public, anon, authenticated;
revoke all on function private.set_updated_at() from public, anon, authenticated;
revoke all on function private.is_active_user(uuid) from public;
revoke all on function private.is_admin(uuid) from public;
grant usage on schema private to authenticated;
grant execute on function private.is_active_user(uuid) to authenticated;
grant execute on function private.is_admin(uuid) to authenticated;

insert into public.stores (slug, name, platform, active) values
  ('bloodmoon-games', 'BloodMoon Games', 'woocommerce', true),
  ('card-nexus', 'Card Nexus', 'woocommerce', true),
  ('cartas-la-fortaleza', 'Cartas La Fortaleza', 'woocommerce', true),
  ('cartas-magic-sur', 'Cartas Magic Sur', 'woocommerce', true),
  ('cat-lotus', 'Cat Lotus', 'woocommerce', true),
  ('dragon-durmiente', 'Dragon Durmiente', 'woocommerce', true),
  ('game-of-magic', 'Game of Magic', 'woocommerce', true),
  ('gamequest', 'Gamequest', 'woocommerce', true),
  ('ineko-card-shop', 'Ineko Card Shop', 'woocommerce', true),
  ('la-comarca', 'La Comarca', 'woocommerce', true),
  ('la-cripta', 'La Cripta', 'woocommerce', true),
  ('magicsur', 'MagicSur', 'woocommerce', true),
  ('rhystic-bazaar', 'Rhystic Bazaar', 'woocommerce', true),
  ('singles-winterland', 'Singles Winterland', 'woocommerce', true),
  ('valhalla-store', 'Valhalla Store', 'woocommerce', true),
  ('card-souls', 'Card Souls', 'shopify', true),
  ('magic4ever', 'Magic4Ever', 'shopify', true),
  ('oasis-games', 'Oasis Games', 'shopify', true),
  ('pay-to-win', 'Pay to Win', 'shopify', true),
  ('piedra-bruja', 'Piedra Bruja', 'shopify', true),
  ('zendicard', 'Zendicard', 'shopify', true),
  ('chronomagic', 'Chronomagic', 'jumpseller', true),
  ('marketplace-scry', 'Marketplace Scry', 'marketplace', true)
on conflict (slug) do update set
  name = excluded.name,
  platform = excluded.platform,
  active = excluded.active;

alter table public.profiles enable row level security;
alter table public.stores enable row level security;
alter table public.favorite_stores enable row level security;
alter table public.wishlist_items enable row level security;
alter table public.search_runs enable row level security;
alter table public.search_cards enable row level security;
alter table public.search_results enable row level security;
alter table public.cart_events enable row level security;
alter table public.admin_audit_log enable row level security;

drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles
for select to authenticated
using (id = auth.uid() and private.is_active_user(auth.uid()));

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles
for update to authenticated
using (id = auth.uid() and private.is_active_user(auth.uid()))
with check (id = auth.uid() and private.is_active_user(auth.uid()));

drop policy if exists stores_read_active on public.stores;
create policy stores_read_active on public.stores
for select to anon, authenticated
using (active = true);

drop policy if exists favorites_own_all on public.favorite_stores;
create policy favorites_own_all on public.favorite_stores
for all to authenticated
using (user_id = auth.uid() and private.is_active_user(auth.uid()))
with check (user_id = auth.uid() and private.is_active_user(auth.uid()));

drop policy if exists wishlist_own_all on public.wishlist_items;
create policy wishlist_own_all on public.wishlist_items
for all to authenticated
using (user_id = auth.uid() and private.is_active_user(auth.uid()))
with check (user_id = auth.uid() and private.is_active_user(auth.uid()));

drop policy if exists search_runs_own_all on public.search_runs;
create policy search_runs_own_all on public.search_runs
for all to authenticated
using (user_id = auth.uid() and private.is_active_user(auth.uid()))
with check (user_id = auth.uid() and private.is_active_user(auth.uid()));

drop policy if exists search_cards_own_all on public.search_cards;
create policy search_cards_own_all on public.search_cards
for all to authenticated
using (
  private.is_active_user(auth.uid()) and exists (
    select 1 from public.search_runs r
    where r.id = search_run_id and r.user_id = auth.uid()
  )
)
with check (
  private.is_active_user(auth.uid()) and exists (
    select 1 from public.search_runs r
    where r.id = search_run_id and r.user_id = auth.uid()
  )
);

drop policy if exists search_results_own_all on public.search_results;
create policy search_results_own_all on public.search_results
for all to authenticated
using (
  private.is_active_user(auth.uid()) and exists (
    select 1
    from public.search_cards c
    join public.search_runs r on r.id = c.search_run_id
    where c.id = search_card_id and r.user_id = auth.uid()
  )
)
with check (
  private.is_active_user(auth.uid()) and exists (
    select 1
    from public.search_cards c
    join public.search_runs r on r.id = c.search_run_id
    where c.id = search_card_id and r.user_id = auth.uid()
  )
);

drop policy if exists cart_events_own_all on public.cart_events;
create policy cart_events_own_all on public.cart_events
for all to authenticated
using (user_id = auth.uid() and private.is_active_user(auth.uid()))
with check (user_id = auth.uid() and private.is_active_user(auth.uid()));

revoke all on all tables in schema public from anon, authenticated;
grant select on public.stores to anon, authenticated;
grant select on public.profiles to authenticated;
grant update (display_name, deletion_requested_at, last_seen_at) on public.profiles to authenticated;
grant select, insert, delete on public.favorite_stores to authenticated;
grant select, insert, update, delete on public.wishlist_items to authenticated;
grant select, insert, update, delete on public.search_runs to authenticated;
grant select, insert, update, delete on public.search_cards to authenticated;
grant select, insert, update, delete on public.search_results to authenticated;
grant select, insert, delete on public.cart_events to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace view public.admin_user_summary
with (security_invoker = true)
as
select
  p.id,
  p.email,
  p.display_name,
  p.avatar_url,
  p.provider,
  p.role,
  p.status,
  p.last_seen_at,
  p.deletion_requested_at,
  p.created_at,
  count(distinct w.id) as wishlist_count,
  count(distinct f.store_id) as favorite_store_count,
  count(distinct s.id) as search_count,
  count(distinct c.id) as cart_event_count
from public.profiles p
left join public.wishlist_items w on w.user_id = p.id
left join public.favorite_stores f on f.user_id = p.id
left join public.search_runs s on s.user_id = p.id
left join public.cart_events c on c.user_id = p.id
group by p.id;

revoke all on public.admin_user_summary from public, anon, authenticated;
grant select on public.admin_user_summary to service_role;

create or replace function private.purge_expired_user_data()
returns table (deleted_searches bigint, deleted_cart_events bigint)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  searches_count bigint;
  carts_count bigint;
begin
  delete from public.search_runs where created_at < now() - interval '90 days';
  get diagnostics searches_count = row_count;

  delete from public.cart_events where created_at < now() - interval '12 months';
  get diagnostics carts_count = row_count;

  return query select searches_count, carts_count;
end;
$$;

revoke all on function private.purge_expired_user_data() from public, anon, authenticated;

do $$
declare
  existing_job bigint;
begin
  select jobid into existing_job from cron.job where jobname = 'purge-mtg-user-history';
  if existing_job is not null then
    perform cron.unschedule(existing_job);
  end if;
  perform cron.schedule(
    'purge-mtg-user-history',
    '17 4 * * *',
    'select * from private.purge_expired_user_data()'
  );
end
$$;

do $$
begin
  if to_regprocedure('public.rls_auto_enable()') is not null then
    revoke all on function public.rls_auto_enable() from public, anon, authenticated;
  end if;
end
$$;
