-- Wishlist price tracker: user configuration, durable queue, observations and email outbox.

alter table public.wishlist_items
  add column if not exists target_price_clp integer check (target_price_clp is null or target_price_clp > 0),
  add column if not exists price_alert_enabled boolean not null default false,
  add column if not exists price_alert_generation integer not null default 0 check (price_alert_generation >= 0),
  add column if not exists last_price_clp integer check (last_price_clp is null or last_price_clp >= 0),
  add column if not exists last_price_store text,
  add column if not exists last_price_product text,
  add column if not exists last_price_url text,
  add column if not exists last_price_checked_at timestamptz,
  add column if not exists price_alert_activated_at timestamptz,
  add column if not exists price_alert_triggered_at timestamptz,
  add column if not exists price_alert_sent_at timestamptz;

create index if not exists wishlist_price_tracker_active_idx
  on public.wishlist_items (card_key)
  where price_alert_enabled and not acquired and target_price_clp is not null;

create table if not exists public.price_tracker_runs (
  id uuid primary key default gen_random_uuid(),
  status text not null default 'running' check (status in ('running', 'completed', 'partial', 'failed')),
  card_count integer not null default 0 check (card_count >= 0),
  completed_count integer not null default 0 check (completed_count >= 0),
  failed_count integer not null default 0 check (failed_count >= 0),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  last_error text
);

create unique index if not exists price_tracker_one_active_run_idx
  on public.price_tracker_runs ((true)) where status = 'running';

create table if not exists public.price_tracker_run_cards (
  id uuid primary key default gen_random_uuid(),
  run_id uuid not null references public.price_tracker_runs(id) on delete cascade,
  card_key text not null,
  card_name text not null,
  status text not null default 'pending' check (status in ('pending', 'processing', 'completed', 'failed')),
  attempts integer not null default 0 check (attempts between 0 and 3),
  lease_until timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  unique (run_id, card_key)
);

create index if not exists price_tracker_run_cards_claim_idx
  on public.price_tracker_run_cards (run_id, status, lease_until, created_at);

create table if not exists public.card_price_observations (
  id bigint generated by default as identity primary key,
  run_card_id uuid not null references public.price_tracker_run_cards(id) on delete cascade,
  wishlist_item_id uuid not null references public.wishlist_items(id) on delete cascade,
  price_clp integer check (price_clp is null or price_clp >= 0),
  store_name text,
  product_name text,
  product_url text,
  offers_count integer not null default 0 check (offers_count >= 0),
  observed_at timestamptz not null default now(),
  unique (run_card_id, wishlist_item_id)
);

create index if not exists card_price_observations_wishlist_idx
  on public.card_price_observations (wishlist_item_id, observed_at desc);

create table if not exists public.price_alert_deliveries (
  id uuid primary key default gen_random_uuid(),
  wishlist_item_id uuid not null references public.wishlist_items(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  alert_generation integer not null check (alert_generation >= 1),
  recipient_email text not null,
  card_name text not null,
  target_price_clp integer not null check (target_price_clp > 0),
  current_price_clp integer not null check (current_price_clp >= 0),
  store_name text not null,
  product_name text not null,
  product_url text not null,
  status text not null default 'pending' check (status in ('pending', 'sending', 'sent', 'failed')),
  attempts integer not null default 0 check (attempts between 0 and 3),
  lease_until timestamptz,
  provider_message_id text,
  last_error text,
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  unique (wishlist_item_id, alert_generation)
);

create index if not exists price_alert_deliveries_claim_idx
  on public.price_alert_deliveries (status, lease_until, created_at);

create table if not exists private.price_tracker_request_nonces (
  nonce uuid primary key,
  used_at timestamptz not null default now()
);

create or replace view public.admin_price_tracker_metrics
with (security_invoker = true)
as
select
  (select count(*) from public.wishlist_items where price_alert_enabled and not acquired) as active_alerts,
  (select count(*) from public.price_alert_deliveries where status = 'sent') as sent_alerts,
  (select count(*) from public.price_alert_deliveries where status = 'failed') as failed_alerts,
  (select count(*) from public.price_alert_deliveries where status in ('pending', 'sending')) as pending_alerts,
  (select started_at from public.price_tracker_runs order by started_at desc limit 1) as last_run_started_at,
  (select status from public.price_tracker_runs order by started_at desc limit 1) as last_run_status;

revoke all on public.admin_price_tracker_metrics from public, anon, authenticated;
grant select on public.admin_price_tracker_metrics to service_role;

create or replace function private.wishlist_tracker_guard()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  if new.acquired then
    new.price_alert_enabled := false;
  end if;
  if new.target_price_clp is null then
    new.price_alert_enabled := false;
  end if;
  return new;
end;
$$;

drop trigger if exists wishlist_tracker_guard on public.wishlist_items;
create trigger wishlist_tracker_guard
before insert or update on public.wishlist_items
for each row execute function private.wishlist_tracker_guard();

create or replace function public.configure_wishlist_price_alert(
  p_item_id uuid,
  p_target_price_clp integer,
  p_enabled boolean default true
)
returns public.wishlist_items
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  current_item public.wishlist_items;
  result_item public.wishlist_items;
  reactivate boolean;
begin
  if not private.is_active_user(auth.uid()) then raise exception 'active user required' using errcode = '42501'; end if;
  if p_target_price_clp is not null and (p_target_price_clp < 1 or p_target_price_clp > 100000000) then
    raise exception 'target price out of range' using errcode = '22023';
  end if;

  select * into current_item from public.wishlist_items
  where id = p_item_id and user_id = auth.uid() for update;
  if not found then raise exception 'wishlist item not found' using errcode = 'P0002'; end if;
  if current_item.acquired and coalesce(p_enabled, false) then
    raise exception 'acquired cards cannot enable alerts' using errcode = '22023';
  end if;

  reactivate := coalesce(p_enabled, false) and (
    not current_item.price_alert_enabled
    or current_item.target_price_clp is distinct from p_target_price_clp
    or current_item.price_alert_triggered_at is not null
  );

  update public.wishlist_items set
    target_price_clp = p_target_price_clp,
    price_alert_enabled = coalesce(p_enabled, false) and p_target_price_clp is not null,
    price_alert_generation = price_alert_generation + case when reactivate then 1 else 0 end,
    price_alert_activated_at = case when reactivate then now() else price_alert_activated_at end,
    price_alert_triggered_at = case when reactivate then null else price_alert_triggered_at end,
    price_alert_sent_at = case when reactivate then null else price_alert_sent_at end
  where id = p_item_id
  returning * into result_item;
  return result_item;
end;
$$;

create or replace function public.start_or_resume_price_tracker_run()
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare run_id uuid;
begin
  select id into run_id from public.price_tracker_runs where status = 'running' order by started_at limit 1;
  if run_id is null then
    insert into public.price_tracker_runs default values returning id into run_id;
    insert into public.price_tracker_run_cards (run_id, card_key, card_name)
    select run_id, card_key, min(card_name)
    from public.wishlist_items
    where price_alert_enabled and not acquired and target_price_clp is not null
    group by card_key;
    update public.price_tracker_runs r set card_count = (
      select count(*) from public.price_tracker_run_cards c where c.run_id = r.id
    ) where r.id = run_id;
    update public.price_tracker_runs set status = 'completed', completed_at = now()
      where id = run_id and card_count = 0;
  end if;
  return run_id;
end;
$$;

create or replace function public.claim_price_tracker_card(p_run_id uuid)
returns table (id uuid, card_key text, card_name text, attempts integer)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  return query
  with candidate as (
    select c.id from public.price_tracker_run_cards c
    where c.run_id = p_run_id
      and c.attempts < 3
      and (c.status = 'pending' or (c.status = 'processing' and c.lease_until < now()))
    order by c.created_at for update skip locked limit 1
  )
  update public.price_tracker_run_cards c set
    status = 'processing', attempts = c.attempts + 1,
    lease_until = now() + interval '15 minutes', last_error = null
  from candidate where c.id = candidate.id
  returning c.id, c.card_key, c.card_name, c.attempts;
end;
$$;

create or replace function public.record_price_tracker_result(
  p_run_card_id uuid, p_price_clp integer, p_store_name text,
  p_product_name text, p_product_url text, p_offers_count integer
)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare queued integer := 0; item record;
begin
  for item in
    select w.*, p.email from public.wishlist_items w join public.profiles p on p.id = w.user_id
    join public.price_tracker_run_cards c on c.card_key = w.card_key
    where c.id = p_run_card_id and w.price_alert_enabled and not w.acquired and w.target_price_clp is not null
    for update of w
  loop
    insert into public.card_price_observations
      (run_card_id, wishlist_item_id, price_clp, store_name, product_name, product_url, offers_count)
    values (p_run_card_id, item.id, p_price_clp, p_store_name, p_product_name, p_product_url, greatest(coalesce(p_offers_count, 0), 0))
    on conflict (run_card_id, wishlist_item_id) do nothing;

    update public.wishlist_items set
      last_price_clp = p_price_clp, last_price_store = p_store_name,
      last_price_product = p_product_name, last_price_url = p_product_url,
      last_price_checked_at = now()
    where id = item.id;

    if p_price_clp is not null and p_price_clp <= item.target_price_clp
       and item.price_alert_triggered_at is null then
      insert into public.price_alert_deliveries
        (wishlist_item_id, user_id, alert_generation, recipient_email, card_name,
         target_price_clp, current_price_clp, store_name, product_name, product_url)
      values (item.id, item.user_id, item.price_alert_generation, item.email, item.card_name,
              item.target_price_clp, p_price_clp, coalesce(p_store_name, 'Tienda'),
              coalesce(p_product_name, item.card_name), coalesce(p_product_url, ''))
      on conflict (wishlist_item_id, alert_generation) do nothing;
      if found then
        queued := queued + 1;
        update public.wishlist_items set price_alert_enabled = false, price_alert_triggered_at = now() where id = item.id;
      end if;
    end if;
  end loop;
  return queued;
end;
$$;

create or replace function public.finish_price_tracker_card(p_run_card_id uuid, p_error text default null)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare affected_run uuid; final_status text;
begin
  update public.price_tracker_run_cards set
    status = case when p_error is null then 'completed' when attempts >= 3 then 'failed' else 'pending' end,
    lease_until = null, last_error = left(p_error, 2000),
    completed_at = case when p_error is null or attempts >= 3 then now() else null end
  where id = p_run_card_id returning run_id into affected_run;

  update public.price_tracker_runs r set
    completed_count = (select count(*) from public.price_tracker_run_cards where run_id = affected_run and status = 'completed'),
    failed_count = (select count(*) from public.price_tracker_run_cards where run_id = affected_run and status = 'failed'),
    last_error = case when p_error is null then r.last_error else left(p_error, 2000) end
  where r.id = affected_run;

  if not exists (select 1 from public.price_tracker_run_cards where run_id = affected_run and status in ('pending', 'processing')) then
    select case when exists (select 1 from public.price_tracker_run_cards where run_id = affected_run and status = 'failed')
      then 'partial' else 'completed' end into final_status;
    update public.price_tracker_runs set status = final_status, completed_at = now() where id = affected_run;
  end if;
end;
$$;

create or replace function public.claim_price_alert_delivery()
returns setof public.price_alert_deliveries
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  return query
  with candidate as (
    select d.id from public.price_alert_deliveries d
    where d.attempts < 3 and (d.status = 'pending' or (d.status = 'sending' and d.lease_until < now()))
    order by d.created_at for update skip locked limit 1
  )
  update public.price_alert_deliveries d set status = 'sending', attempts = d.attempts + 1,
    lease_until = now() + interval '15 minutes', last_error = null
  from candidate where d.id = candidate.id returning d.*;
end;
$$;

create or replace function public.finish_price_alert_delivery(
  p_delivery_id uuid, p_provider_message_id text default null, p_error text default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare linked_item uuid; delivered_at timestamptz;
begin
  delivered_at := case when p_error is null then now() else null end;
  update public.price_alert_deliveries set
    status = case when p_error is null then 'sent' when attempts >= 3 then 'failed' else 'pending' end,
    lease_until = null, provider_message_id = p_provider_message_id,
    last_error = left(p_error, 2000), sent_at = delivered_at
  where id = p_delivery_id returning wishlist_item_id into linked_item;
  if delivered_at is not null then
    update public.wishlist_items set price_alert_sent_at = delivered_at where id = linked_item;
  end if;
end;
$$;

create or replace function public.claim_price_tracker_nonce(p_nonce uuid)
returns boolean
language plpgsql
security definer
set search_path = private, pg_temp
as $$
begin
  delete from private.price_tracker_request_nonces where used_at < now() - interval '10 minutes';
  insert into private.price_tracker_request_nonces(nonce) values (p_nonce);
  return true;
exception when unique_violation then return false;
end;
$$;

alter table public.price_tracker_runs enable row level security;
alter table public.price_tracker_run_cards enable row level security;
alter table public.card_price_observations enable row level security;
alter table public.price_alert_deliveries enable row level security;

create policy tracker_observations_own_read on public.card_price_observations
for select to authenticated using (exists (
  select 1 from public.wishlist_items w where w.id = wishlist_item_id and w.user_id = auth.uid()
));
create policy tracker_deliveries_own_read on public.price_alert_deliveries
for select to authenticated using (user_id = auth.uid() and private.is_active_user(auth.uid()));

revoke all on public.price_tracker_runs, public.price_tracker_run_cards,
  public.card_price_observations, public.price_alert_deliveries from public, anon, authenticated;
grant select on public.card_price_observations, public.price_alert_deliveries to authenticated;

revoke update on public.wishlist_items from authenticated;
grant update (desired_quantity, notes, acquired) on public.wishlist_items to authenticated;

revoke all on function public.configure_wishlist_price_alert(uuid, integer, boolean) from public, anon;
grant execute on function public.configure_wishlist_price_alert(uuid, integer, boolean) to authenticated;

revoke all on function public.start_or_resume_price_tracker_run(),
  public.claim_price_tracker_card(uuid),
  public.record_price_tracker_result(uuid, integer, text, text, text, integer),
  public.finish_price_tracker_card(uuid, text),
  public.claim_price_alert_delivery(),
  public.finish_price_alert_delivery(uuid, text, text),
  public.claim_price_tracker_nonce(uuid)
from public, anon, authenticated;
grant execute on function public.start_or_resume_price_tracker_run(),
  public.claim_price_tracker_card(uuid),
  public.record_price_tracker_result(uuid, integer, text, text, text, integer),
  public.finish_price_tracker_card(uuid, text),
  public.claim_price_alert_delivery(),
  public.finish_price_alert_delivery(uuid, text, text),
  public.claim_price_tracker_nonce(uuid)
to service_role;

revoke all on function private.wishlist_tracker_guard() from public, anon, authenticated;
